version: '2'
services:
  pgtbackend-app:
    image: pgtbackend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgtbackend-postgresql:5432/pgtBackend
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  pgtbackend-postgresql:
    extends:
      file: postgresql.yml
      service: pgtbackend-postgresql
